version: '3.8'
services:
  middleware:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simplified-paperless-bigcapital-middleware
    ports:
      - "5000:5000"
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
      - ../data:/app/data
    environment:
      - FLASK_ENV=production
      - CONFIG_FILE=config.ini
    depends_on:
      - paperless-ngx
      - gotenberg  # Added for enhanced document processing
      - tika        # Added for better parsing
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - paperless-redis
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - paperless_export:/usr/src/paperless/export
      - ../uploads:/usr/src/paperless/consume
    environment:
      # Redis configuration
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_SECRET_KEY: change-me-please-in-production # <<< IMPORTANT: Change this!
      PAPERLESS_URL: http://paperless-ngx:8000
      PAPERLESS_TIME_ZONE: Australia/Perth
      
      # Enhanced OCR Configuration
      PAPERLESS_OCR_LANGUAGE: eng  # English 
      PAPERLESS_OCR_MODE: redo         # Options: skip, redo, force
      PAPERLESS_OCR_CLEAN: clean       # Options: clean, clean-final, none
      PAPERLESS_OCR_DESKEW: "true"     # Correct skewed scans
      PAPERLESS_OCR_ROTATE_PAGES: "true" # Auto-rotate pages
      PAPERLESS_OCR_PAGES: "0"         # 0 = process all pages
      PAPERLESS_OCR_IMAGE_DPI: "300"   # Higher DPI for better OCR accuracy
      
      # Document processing improvements
      PAPERLESS_OCR_OUTPUT_TYPE: pdfa-2 # PDF/A format for better compatibility
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: never # Always create archive files
      
      # Tika integration for better parsing
      PAPERLESS_TIKA_ENABLED: "true"
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      
      # Memory and performance
      PAPERLESS_CONVERT_MEMORY_LIMIT: 256MB
      PAPERLESS_TASK_WORKERS: "1"
      PAPERLESS_THREADS_PER_WORKER: "1"
      
      # Consumer settings for better file processing
      PAPERLESS_CONSUMER_POLLING: "0"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
      
      # Receipt/invoice processing optimization
      PAPERLESS_FILENAME_FORMAT: "{{ created_year }}/{{ correspondent }}/{{ title }}"
  # Supporting services for enhanced OCR and document processing
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7
    container_name: paperless-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-web-security"
      - "--chromium-allow-list=file:///*"
  tika:
    image: docker.io/apache/tika:latest
    container_name: paperless-tika
    restart: unless-stopped
  paperless-redis:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - paperless_redis:/data
volumes:
  paperless_data:
  paperless_media:
  paperless_export:  # Added for document exports
  paperless_redis:
