version: '3.8'

services:
  middleware:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: paperless_middleware
    ports:
      - "5000:5000"
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
      - ../data:/app/data
    environment:
      - FLASK_ENV=production
      - CONFIG_FILE=config.ini
    depends_on: []

