name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t simplified-paperless-bigcapital-middleware -f docker/Dockerfile .

      - name: Run Tests in Docker Container
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v ${{ github.workspace }}:/app \
            -w /app \
            simplified-paperless-bigcapital-middleware \
            -c "pip install pytest && pytest tests/"

      # --- ADD THESE STEPS TO PUSH TO DOCKER HUB ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # You need to set this as a GitHub Secret
          password: ${{ secrets.DOCKER_PASSWORD }} # You need to set this as a GitHub Secret (Personal Access Token)

      - name: Tag and Push Docker Image to Docker Hub
        run: |
          # Replace 'your_docker_username' with your actual Docker Hub username
          # You might want to use a dynamic tag like latest, or a commit SHA
          docker tag simplified-paperless-bigcapital-middleware caston81/simplified-paperless-bigcapital-middleware:latest
          docker push your_docker_username/simplified-paperless-bigcapital-middleware:latest
      # --- END OF ADDED STEPS ---
